* ACM Bot
** Configuración previa
Hazte con un token hablando a ~@BotFather~ en Telegram.

Crea un archivo llamado ~bot.token~ que contenga únicamente el token,
por ejemplo así:
#+BEGIN_SRC shell
echo "increible_token_que_no_voy_a_subir_a_github" > bot.token
#+END_SRC
** Configuración opcional
Añade un pdf para los precios modificando en el ~Makefile~ la linea:
#+BEGIN_SRC shell
run: export PRICES_PATH = "path/to/file"
#+END_SRC

y en caso de que uses systemd:
#+BEGIN_SRC shell
srun: export PRICES_PATH = "path/to/file"
#+END_SRC

** Ejecución
Ejecuta el bot con:
#+BEGIN_SRC shell
make run
#+END_SRC

Este comando descargará las dependencias necesarias, las compilará,
compilará el proyecto y lo ejecutará. Puedes echarle un vistazo al
~Makefile~ que encontrarás en la raíz del proyecto.

** Subir código
*** Crear una issue
Hay unos templates para las issues, intenta rellenar el máximo número
de puntos a tratar posible.

*** Crear una rama relacionada con la issue
El nombre de la rama tendrá el siguiente formato:
#+BEGIN_SRC
<github_user>/issue_<issue_number>
#+END_SRC

Por ejemplo:
#+BEGIN_SRC
ironjanowar/issue_1
#+END_SRC

*** Crear una Pull Request relacionada a la issue
En esta PR se mencionará la issue y se seleccionará a alguien para que
la revise y la pruebe.

*** Aprobación de PR
La PR una vez aprobada se mergeará a la rama ~develop~.

*** Merge a ~master~
Todavia por definir... ¯\_(ツ)_/¯
